name: READMEmd build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Start the project
        run: npm start
      - name: Generate README file
        run: node dist/index.js
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
